apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{ secret_name }}
  namespace: {{ argocd_namespace }}
type: Opaque
data:
  insecure: dHJ1ZQ==
  project: ZGVmYXVsdA==
  type: Z2l0
  url: {{ repo_url }}
  username: {{ repo_url }}
  password: {{ password }}
  #tlsClientCertKey: {{ tls_client_cert_key }}
