apiVersion: v1
kind: Secret
metadata:
  name: argocd-application-controller-token
  namespace: test-argo #TODO 바꿔주기
  annotations:
    kubernetes.io/service-account.name: argocd-application-controller
type: kubernetes.io/service-account-token
